import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './i18n/config.js'
import './global.css'
import './index.css'
import './responsive.css'
import App from './App.jsx'

// Registers the service worker generated by vite-plugin-pwa.
// registerType: 'autoUpdate' (set in vite.config.js) means a new version is
// fetched and activated in the background automatically — onNeedRefresh
// won't normally fire, but it's wired up in case that ever changes.
// onOfflineReady fires once, the first time the app shell has been fully
// cached and the app can be opened with no network.
registerSW({
  onNeedRefresh() {
    console.log('[PWA] New content available — will apply on next reload.')
  },
  onOfflineReady() {
    console.log('[PWA] App is ready to work offline.')
  },
})

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>
)
